name: Sync to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: digitalocean
          region: 'sgp1'
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}


      - name: Copy files to S3 with the s3cmd
        run: |
            s3cmd sync --recursive --acl-public ./statements/pdf s3://proginth/statements/
